global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  # Scrape the Source Reader every second.
  - job_name: 'source'
    scrape_interval: 1s
    static_configs:
    - targets: ['0.0.0.0:8021']

  # Scrape the Target Writers every second.
  - job_name: 'target'
    scrape_interval: 1s
    static_configs:
    - targets: ['0.0.0.0:8022', '0.0.0.0:8023', '0.0.0.0:8024']
